services:
  springboot:
    image: back
    container_name: back
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/imnotdurnk_db #내부포트 사용
      - MYSQL_USERNAME=ssafy
      - MYSQL_PASSWORD=ssafy
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - network_deploy
    restart: unless-stopped

  react:
    image: front
    container_name: front
    ports:
      - "3333:3000"
    networks:
      - network_deploy
    depends_on:
      - mysql
      - redis
      - springboot

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: imnotdurnk_db
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_deploy

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - network_deploy

volumes:
  mysql_data:
  redis_data:

networks:
  network_deploy:
     driver: bridge
