spring:
  application:
    name: imnotdurnk_backend
    title: 나안취햄ㅅ어
  security: ignored=/**   # 일단 비활성화


  config:
    import: application-secrete.yml


    # DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  # Mail Setting
  mail:
    host: smtp.naver.com
    port: 465
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
jwt:
  expiretime:
    accesstoken: 1800000 #30분
    refreshtoken: 432000000 #5일
  secretkey:
    accesstoken: adfklasdjhlfakjsdhlfjkashdljkfahlsdkjfasdfasd
    refreshtoken: eirouqpiwerupqoiweuoiuXZiucxziuizzzxxccxvbdlkjkc
