spring:
  application:
    name: imnotdurnk_backend
    title: 나안취햄ㅅ어
  security: ignored=/**   # 일단 비활성화

  # ------이거 있으면 오류나유--------
  #config:
  #  import: application-secret.yml
  #---------------------------------

  # DB Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    open-in-view: false
    show-sql: false

  # Mail Setting
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          ssl:
            enable: false
            trust: ${MAIL_HOST}
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

jwt:
  expiretime:
    accesstoken: ${JWT_ACCESS_TOKEN_EXPIRY}
    refreshtoken: ${JWT_REFRESH_TOKEN_EXPIRY}
  secretkey:
    accesstoken: ${JWT_ACCESS_TOKEN_SECRET}
    refreshtoken: ${JWT_REFRESH_TOKEN_SECRET}

etri:
  accessKey: ${ETRI_ACCESS_KEY}

logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    com:
      imnotdurnk:
        domain:
          auth: ${LOG_LEVEL_AUTH}
          calendar: ${LOG_LEVEL_CALENDAR}
          MAP: ${LOG_LEVEL_MAP}
          gamelog: ${LOG_LEVEL_GAMELOG}
          user: ${LOG_LEVEL_USER}
        global:
          util: ${LOG_LEVEL_UTIL}

Odsay:
  apikey: ${ODSAY_API_KEY}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-produces-media-type: application/json